version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing npm i
      - npm i
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build started
      - ng build --configuration production
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes

